name: .NET Core

on:
  push:
    paths: 
    - 'apis/poi/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Install dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore apis/poi/poi.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal apis/poi/poi.sln
